name: Deploy Vendure API
on:
  push:
    branches:
      - develop
      - master

jobs:
  deploy:
    name: Deploy to CloudRun (test and prod)
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: vendure

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: wormenkwekerijwasse
          service_account_key: ${{ secrets.GCLOUD_DEVOPS}}
          export_default_credentials: true
      - name: Build Docker container
        run: ./build.sh
      - name: Set env vars
        run: 'echo "$SECRET_VARS" > .env'
        env:
          SECRET_VARS: ${{secrets.ENVS}}
      - name: Deploy
        run: ./deploy.sh
